# Generated by Django 5.0.1 on 2024-02-03 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category_name',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='articles.category'),
            preserve_default=False,
        ),
    ]
